/* Français — The Human Journey */
window.I18N.fr = {
  places: {
      "origin": "Afrique de l'Est",
      "origin_n": "Afrique du Nord",
      "south_afr": "Afrique australe",
      "west_afr": "Afrique de l'Ouest",
      "levant1": "Le Levant (débuts)",
      "levant2": "Le Levant (débuts)",
      "arabia": "Arabie",
      "south_asia": "Asie du Sud",
      "sahul": "Sahul (Australie)",
      "se_asia": "Asie du Sud-Est",
      "europe": "Europe",
      "c_asia": "Asie centrale",
      "e_asia": "Asie de l'Est",
      "siberia": "Sibérie",
      "beringia": "Béringie",
      "n_america": "Amérique du Nord",
      "s_america": "Amérique du Sud",
      "patagonia": "Patagonie et l'extrême sud",
      "remote_oc": "Pacifique lointain",
      "nz": "Aotearoa (Nouvelle-Zélande)"
  },
  ui: {
    eyebrow: "Un atlas interactif",
    titleA: "Le Voyage", titleB: "Humain",
    credit1: "Hors d'Afrique", credit2: "et les origines de la croyance",
    mapLayers: "Calques de la carte",
    layer_settlement: "Peuplement", layer_migration: "Migration",
    layer_religion: "Religion", layer_population: "Population", layer_ice: "Calottes glaciaires",
    globeType: "Type de globe",
    theme_slate: "Ardoise", theme_relief: "Relief", theme_twilight: "Crépuscule", theme_atlas: "Atlas",
    formsOfBelief: "Formes de croyance", reset: "Réinitialiser",
    legItemTitle: "Cliquer pour cibler · Maj+clic pour basculer",
    humanPopulation: "Population humaine", humansAlive: "Humains vivants",
    play: "Lecture", pause: "Pause",
    yearsAgo: "ans avant nous", yearAgo: "an avant nous",
    today: "Aujourd'hui", presentDay: "Aujourd'hui · 2025",
    onTheMap: "Sur la carte",
    map_region: "Terre peuplée — couleur de la croyance", map_route: "Route migratoire",
    map_settlement: "Peuplement atteint", map_flow: "La croyance se répand", map_pop: "Population (hauteur)",
    hint: "Glisser pour tourner · Molette pour zoomer · Glisser la frise",
    language: "Langue",
    photos: "Photos",
    gallery: "Galerie",
    tick_300ka: "300 ka", tick_ooa: "Hors d'Afrique", tick_villages: "Premiers villages",
    tick_cities: "Premières villes", tick_2ka: "2 ka", tick_today: "Auj.",
  },
  epochs: { palaeolithic: "Paléolithique", neolithic: "Néolithique", bronze: "Âge du bronze",
    iron: "Âge du fer / Antiquité", ce: "Ère commune" },
  era: { bce: "av. J.-C.", ce: "apr. J.-C." },
  story: [
    { k: "≈ Il y a 300 000 ans · Afrique", b: "Un nouveau type d'humain prend forme : Homo sapiens. Non dans un seul berceau mais sur tout le continent à la fois — l'origine panafricaine : un réseau interconnecté de populations, du Maroc à l'Éthiopie au Cap, se fondant peu à peu en nous." },
    { k: "Le berceau africain", b: "Pendant des milliers de générations, ils se répandent seuls sur le continent — du Cap au Sahara — maîtrisant le feu, les outils et le langage." },
    { k: "Il y a ≈ 200 000 ans", b: "Ils enterrent leurs morts, peignent leurs corps d'ocre et commencent à percevoir des esprits dans les animaux, les rivières et la pierre : l'aube de l'animisme." },
    { k: "Premiers pas au-delà", b: "De petites bandes errent au nord, vers le Levant. Mais le monde hors d'Afrique est rude, et ces premières tentatives s'éteignent." },
    { k: "Il y a ≈ 70 000 ans · Hors d'Afrique", b: "Enfin une petite population franchit l'étroite bouche de la mer Rouge. Presque tous ceux qui vivent hors d'Afrique aujourd'hui descendent de ce seul voyage." },
    { k: "La route côtière", b: "Longeant les rivages de l'Arabie et de l'Inde, ils avancent vers l'est à une vitesse stupéfiante, vivant des richesses de la mer." },
    { k: "Il y a ≈ 55 000 ans · Sahul", b: "Traversant la haute mer — les premiers humains à le faire — ils atteignent l'Australie et se lient à la terre par les totems et le Temps du Rêve." },
    { k: "Il y a ≈ 45 000 ans · Europe", b: "D'autres se tournent au nord, vers l'Europe glaciaire. Dans l'obscurité des grottes peintes, les chamanes entrent en transe pour marcher entre les vivants et le monde des esprits." },
    { k: "À travers l'Asie", b: "Des steppes occidentales au Pacifique, les humains emplissent le vaste cœur de l'Asie, atteignant la Chine et la lisière des glaces du nord." },
    { k: "Le Grand Nord gelé", b: "Au plus fort de la dernière glaciation, de robustes chasseurs s'enfoncent en Sibérie, vêtus de fourrures cousues contre le froid mortel." },
    { k: "Il y a ≈ 20 000 ans · Béringie", b: "Tant d'eau est piégée dans la glace qu'un pont terrestre relie l'Asie à l'Amérique. Les chasseurs le traversent vers un Nouveau Monde entièrement vide." },
    { k: "Vers les Amériques", b: "De l'Alaska aux Andes, deux grands continents s'ouvrent devant eux. Ils descendent le Nouveau Monde à une vitesse fulgurante — la dernière grande terre à connaître un pas humain." },
    { k: "Il y a ≈ 13 000 ans", b: "En quelques milliers d'années, ils atteignent la pointe sud de l'Amérique du Sud. L'humanité a désormais touché tous les continents habitables." },
    { k: "La fin de la glaciation", b: "Tandis que le monde se réchauffe, dans le Croissant fertile on s'attarde près des champs de céréales sauvages — et l'on commence, pour la première fois, à rester au même endroit." },
    { k: "Il y a ≈ 11 000 ans · Göbekli Tepe", b: "Avant l'agriculture, avant les villes, ils dressent de grands piliers sculptés sur leurs morts. Les ancêtres deviennent les gardiens des vivants." },
    { k: "Les premiers agriculteurs", b: "Le blé, l'orge, les moutons et les bovins sont domestiqués. Un champ cultivé nourrit bien plus de bouches que la chasse — alors les gens cessent d'errer et s'installent près de leurs récoltes. Les premiers villages permanents prennent racine." },
    { k: "≈ 3300 av. J.-C. · Sumer", b: "Le grain stocké nourrit désormais ceux qui ne cultivent jamais : scribes, prêtres, soldats, rois. En Mésopotamie, les villages gonflés deviennent les premières vraies villes, couronnées de vastes panthéons de dieux." },
    { k: "Dieux des royaumes fluviaux", b: "Le long du Nil et de l'Indus, les temples deviennent les moteurs de l'État, et un clergé lettré inscrit dans le monde la volonté des dieux." },
    { k: "≈ 1350 av. J.-C. · Égypte", b: "Le pharaon Akhénaton exalte un unique dieu solaire au-dessus de tous les autres — un pas bref et radical vers l'adoration d'un seul dieu." },
    { k: "≈ 1000 av. J.-C. · Perse", b: "En Iran, le prophète Zarathoustra repense le cosmos comme une lutte entre le bien et le mal — un dualisme qui résonnera pendant des millénaires." },
    { k: "≈ 600 av. J.-C. · Juda", b: "En exil à Babylone, le peuple de Juda déclare son dieu unique créateur de toutes choses — le premier monothéisme durable." },
    { k: "≈ 500 av. J.-C. · La Méditerranée", b: "Autour de la Méditerranée, la Grèce et Rome font de leurs dieux des citoyens — patrons des cités, des fêtes et des jeux, vénérés comme un devoir public." },
    { k: "≈ Ier–IVe siècle apr. J.-C. · Christianisme", b: "Depuis la Méditerranée orientale, le christianisme porte l'idée d'un Dieu unique à travers le monde romain — et, avec le temps, bien au-delà." },
    { k: "≈ VIIe siècle apr. J.-C. · Islam", b: "En Arabie, l'islam surgit et se répand avec une rapidité extraordinaire — à l'ouest vers l'Espagne et à travers le Sahara, et à l'est jusqu'à l'Indus et la côte swahilie." },
    { k: "Le dernier grand voyage", b: "Loin à l'est, dans les mers chaudes de l'Asie du Sud-Est insulaire, les plus grands navigateurs qui aient jamais existé s'élancent dans le Pacifique ouvert : la dernière grande migration humaine commence." },
    { k: "Sur l'océan le plus lointain", b: "Lisant la houle, les étoiles et les oiseaux, ils bondissent d'île en île sur des milliers de kilomètres de mer vide, peuplant les dernières parcelles de terre éparses du globe." },
    { k: "Aotearoa · la dernière terre", b: "Leur ultime voyage les porte au sud, vers la Nouvelle-Zélande — la dernière grande terre du globe que les êtres humains atteindraient jamais." },
    { k: "≈ 1500 apr. J.-C. · Un monde entrelacé", b: "Les navires relient enfin les continents. Les Européens franchissent les océans, et peuples, cultures et dieux circulent entre les mondes comme jamais — le christianisme suivant l'empire et le commerce vers les Amériques et à travers l'Afrique." },
    { k: "Aujourd'hui", b: "En à peine deux siècles, l'humanité passe d'un à huit milliards. D'un unique commencement africain, notre espèce emplit désormais la planète — chaque continent habitable habité —, portant tout le long héritage de la croyance, des premiers esprits à une unique divinité exclusive." },
  ],
  religions: {
    animism: { name: "Animisme", blurb: "La plus ancienne et la plus répandue des façons de voir le monde : tout — animaux, rivières, pierres, climat, les morts — est vivant, doté d'esprit et d'intention. Moins une doctrine qu'une posture humaine par défaut face à un cosmos vivant.", examples: "Chasseurs-cueilleurs san d'Afrique australe · peuples amazoniens · cultures circumpolaires", when: "Dès le Paléolithique moyen (~100 000 ans)" },
    shamanism: { name: "Chamanisme", blurb: "Des spécialistes — les chamanes — entrent en transe pour voyager entre le monde humain et celui des esprits, guérissant, divinant et guidant la chasse. Les grottes peintes de l'Europe glaciaire et de la Sibérie en conservent les plus anciennes traces.", examples: "Peintres de Chauvet et Lascaux · peuples toungouses de Sibérie (le mot « chamane » est évenk)", when: "Paléolithique supérieur (~48 000 ans)" },
    totemism: { name: "Totémisme", blurb: "Les clans se lient à un totem — un animal, une plante, un lieu — qui marque l'identité, la parenté et l'obligation. En Australie aborigène, ces liens sont tissés dans le Temps du Rêve, le paysage éternel des êtres ancestraux.", examples: "Nations aborigènes d'Australie · de nombreux systèmes claniques d'Amérique du Nord et d'Afrique", when: "Vivace en Australie aborigène (~50 000 ans)" },
    ancestor: { name: "Culte des ancêtres", blurb: "En s'installant dans des villages, les morts restèrent proches. Les ancêtres devinrent gardiens de la terre, de la lignée et de la loi, honorés d'offrandes, de crânes entretenus et des premiers sanctuaires monumentaux.", examples: "Göbekli Tepe (~11 000 ans) · Çatalhöyük · rites ancestraux chinois ultérieurs", when: "Néolithique (~12 000 ans)" },
    polytheism: { name: "Polythéisme archaïque", blurb: "Les premières cités avaient besoin de dieux aussi vastes et bureaucratiques qu'elles. Les panthéons régissaient le ciel, l'orage, le grain et les enfers ; les temples devinrent les moteurs des premiers États, servis par un clergé lettré.", examples: "Sumer et Babylone · Égypte · l'Indus et la Chine ancienne", when: "Âge du bronze (dès ~3200 av. J.-C.)" },
    civic: { name: "Polythéisme civique", blurb: "Dans la Méditerranée classique, les dieux devinrent aussi des citoyens : patrons des cités, des fêtes et des jeux. La religion était devoir public et identité partagée autant que croyance privée.", examples: "Cités-États grecques · culte d'État romain · traditions védiques puis hindoues", when: "Antiquité classique (~900 av. J.-C. – 400 apr. J.-C.)" },
    dualism: { name: "Dualisme", blurb: "Le cosmos reconçu comme un champ de bataille moral : un bien suprême aux prises avec un principe du mal, les choix humains faisant pencher la balance. La vision de Zoroastre en Perse résonnera dans les fois ultérieures.", examples: "Zoroastrisme en Perse · plus tard le manichéisme", when: "Perse de l'âge du fer (~1000–700 av. J.-C.)" },
    henotheism: { name: "Hénothéisme et monolâtrie", blurb: "Un point de bascule : de nombreux dieux sont reconnus, mais un seul est exalté au-dessus de tous — ou seul mérite le culte. La brève révolution solaire d'Akhénaton et la dévotion du premier Israël à Yahvé jalonnent la route vers un Dieu unique.", examples: "Culte d'Aton d'Akhénaton (~1350 av. J.-C.) · yahvisme israélite ancien", when: "Bronze tardif / fer ancien (~1400–600 av. J.-C.)" },
    judaism: { name: "Judaïsme", blurb: "Un seul Dieu, créateur de tout — soutenu durablement pour la première fois par les Judéens dans l'Israël de l'âge du fer et l'exil de Babylone. La racine d'où grandiront les autres fois abrahamiques.", examples: "Israël et Juda · l'exil babylonien (~VIe s. av. J.-C.) · la diaspora juive", when: "Dès l'âge du fer (~600 av. J.-C.)" },
    christianity: { name: "Christianisme", blurb: "Né dans la Judée romaine, le christianisme porta l'idée d'un Dieu unique à travers l'Empire et, par conviction, conquête et colonie, jusqu'en Europe, aux Amériques et en Afrique : la foi la plus répandue de la Terre.", examples: "Empire romain (~Ier s. apr. J.-C.) · Europe médiévale · Amériques et Afrique (dès le XVIe s.)", when: "Dès le Ier siècle apr. J.-C." },
    islam: { name: "Islam", blurb: "Né dans l'Arabie du VIIe siècle, l'islam se répandit avec une rapidité extraordinaire — à l'ouest jusqu'à la péninsule Ibérique, au sud à travers le Sahara et la côte swahilie, et à l'est jusqu'à l'Indus et au-delà.", examples: "Arabie (~VIIe s. apr. J.-C.) · les califats · le Sahel, la côte swahilie et l'Asie du Sud", when: "Dès le VIIe siècle apr. J.-C." },
  },
  chapters: [
    { t: "Une aube africaine", b: "Il y a environ 300 000 ans, dans les savanes et sur les côtes d'Afrique, apparaît un nouveau type d'humain : Homo sapiens. De constitution plus légère et à l'esprit inquiet, il se répand sur le continent bien avant de le quitter." },
    { t: "Un continent exploré", b: "Pendant plus de cent millénaires, les humains modernes parcourent l'Afrique, affinant outils, pigments et parures, et peut-être les premières croyances que le monde est vivant d'esprit." },
    { t: "Hors d'Afrique", b: "Il y a environ 70 000 ans, une petite population franchit la bouche de la mer Rouge vers l'Arabie. Tout non-Africain vivant aujourd'hui descend largement de cette dispersion : un voyage qui atteindra tous les continents habitables." },
    { t: "Un monde de chasseurs", b: "Les humains déferlent sur l'Australie, l'Europe et le cœur de l'Asie. Dans les grottes peintes et la transe, les chamanes relient les mondes ; les clans se lient aux totems et à la terre." },
    { t: "La glace et le Nouveau Monde", b: "À travers la dernière glaciation, les chasseurs s'enfoncent en Sibérie et franchissent le pont de Béringie vers les Amériques, courant au sud jusqu'à la pointe du continent en quelques milliers d'années." },
    { t: "Les premiers villages", b: "À mesure que la glace recule, on s'installe, on cultive, on bâtit. Les morts demeurent parmi les vivants comme ancêtres honorés ; à Göbekli Tepe, on dresse des monuments avant des villes." },
    { t: "Dieux des premières villes", b: "En Mésopotamie et en Égypte, les premiers États se couronnent de grands panthéons. Les temples emmagasinent grain et savoir ; un clergé inscrit dans le monde la volonté des dieux." },
    { t: "Un âge de ferment", b: "De la Perse à la Méditerranée et à l'Inde, de nouvelles visions s'agitent — dualisme cosmique, dieux civiques, et l'idée audacieuse qu'un seul Dieu pourrait s'élever au-dessus de tous les autres, ou à leur place." },
    { t: "Un Dieu, des peuples multiples", b: "Porté par l'empire, le commerce et la conviction, le monothéisme abrahamique se répand sur les continents. Les descendants d'une unique population africaine emplissent désormais la Terre — et portent avec eux tout le long héritage de la croyance." },
  ],
  about: {
    open: "À propos", close: "Fermer",
    title: "À propos de cet atlas",
    intro: "Le Voyage Humain suit notre espèce sur 300 000 ans — hors d'Afrique vers chaque continent habitable — et retrace, aux côtés de cette grande migration, le déploiement de la croyance humaine, du premier sentiment des esprits aux religions du monde.",
    s: [
      { h: "Ce que vous voyez", b: "Un seul globe porte toutes les couches à la fois. La terre lumineuse est une terre peuplée, teintée de la couleur de la croyance qu'on y tient. Les lignes cyan en pointillés sont des routes migratoires ; les points brillants marquent les peuplements atteints. Les flux colorés montrent les croyances se répandant d'un lieu à l'autre, et les flèches roses sont la population — basses dans la préhistoire profonde, vertigineuses à l'âge des villes. Les calottes blanches sont la glace polaire, qui croît et reflue au gré des glaciations." },
      { h: "Comment naviguer", b: "Appuyez sur Lecture (ou la barre d'espace) pour mettre l'histoire en mouvement ; la caméra, les légendes et la frise avancent ensemble. Utilisez les touches ← et → pour avancer image par image (ou Maj + ← et → pour des sauts plus rapides), ou glissez la frise pour voyager librement. Glissez le globe pour le faire tourner et utilisez la molette pour zoomer. Cliquez sur une croyance dans le panneau Formes de croyance pour la lire et recentrer la vue ; les panneaux Calques de la carte et Type de globe permettent d'afficher, masquer et restyler chaque élément." },
      { h: "Comme outil pédagogique", b: "Mettez en pause à tout moment pour en discuter. Suivez comment l'environnement façonne la migration, et comment peuplement, agriculture, villes et croyance s'élèvent ensemble. Basculez les couches pour isoler un seul fil — la migration seule, ou la religion seule — et faites passer le graphique de population du linéaire au logarithmique pour montrer combien notre explosion démographique est récente. Les légendes se lisent comme un script narré pour une classe." },
      { h: "Pourquoi nous l'avons fait", b: "Non pour argumenter, mais pour s'émerveiller. Cet atlas a été conçu pour que chacun puisse prendre du recul et embrasser le long et improbable arc des origines humaines : un seul commencement africain, agité, qui, en dix mille générations, en vint à emplir la Terre entière et à s'en émerveiller." },
    ],
    learnMore: {
      h: "En savoir plus",
      b: "Cet atlas est une synthèse, non une source. Pour approfondir la migration, la génétique et l'histoire de la croyance, voici de bons points de départ :",
      links: [
        { label: "Smithsonian — What Does It Mean to Be Human?", url: "https://humanorigins.si.edu/", note: "évolution et origines humaines" },
        { label: "Bradshaw Foundation — The Journey of Mankind", url: "https://www.bradshawfoundation.com/journey/", note: "carte génétique de la migration" },
        { label: "Our World in Data — Population Growth", url: "https://ourworldindata.org/population-growth", note: "la longue courbe démographique" },
        { label: "Britannica — The Study of Religion", url: "https://www.britannica.com/topic/study-of-religion", note: "l'histoire de la croyance" },
        { label: "Y. N. Harari — Sapiens", url: "https://www.ynharari.com/book/sapiens-2/", note: "une brève histoire de l'humanité" },
      ],
    },
  },
};
