/* Català — The Human Journey */
window.I18N.ca = {
  places: {
      "origin": "Àfrica Oriental",
      "origin_n": "Àfrica del Nord",
      "south_afr": "Àfrica Austral",
      "west_afr": "Àfrica Occidental",
      "levant1": "El Llevant (inicis)",
      "levant2": "El Llevant (inicis)",
      "arabia": "Aràbia",
      "south_asia": "Sud d'Àsia",
      "sahul": "Sahul (Austràlia)",
      "se_asia": "Sud-est asiàtic",
      "europe": "Europa",
      "c_asia": "Àsia Central",
      "e_asia": "Àsia Oriental",
      "siberia": "Sibèria",
      "beringia": "Beríngia",
      "n_america": "Amèrica del Nord",
      "s_america": "Amèrica del Sud",
      "patagonia": "Patagònia i l'extrem sud",
      "remote_oc": "Pacífic remot",
      "nz": "Aotearoa (Nova Zelanda)"
  },
  ui: {
    eyebrow: "Un atles interactiu",
    explore: "Explora", youAreHere: "Ets aquí",
    nav_globe: "El Viatge Humà", nav_globe_note: "Fora d'Àfrica — l'atles",
    nav_freedom: "Poder i llibertat", nav_freedom_note: "Part VI · la teoria de la llibertat",
    nav_origins: "Els orígens del poder", nav_origins_note: "Part I · els mecanismes",
    nav_iq: "Poder, riquesa i desigualtat", nav_iq_note: "Part II · les quantitats",
    nav_cast: "El repartiment i la màquina", nav_cast_note: "Part III · rols i l'estat",
    titleA: "El Viatge", titleB: "Humà",
    credit1: "Fora d'Àfrica", credit2: "i els orígens de la creença",
    mapLayers: "Capes del mapa",
    layer_settlement: "Poblament", layer_migration: "Migració",
    layer_religion: "Religió", layer_population: "Població", layer_ice: "Casquets de gel",
    globeType: "Tipus de globus",
    theme_slate: "Pissarra", theme_relief: "Relleu", theme_twilight: "Crepuscle", theme_atlas: "Atles",
    formsOfBelief: "Formes de creença", reset: "Reiniciar",
    legItemTitle: "Clic per enfocar · Maj+clic per alternar",
    humanPopulation: "Població humana", humansAlive: "Humans vius",
    play: "Reproduir", pause: "Pausa",
    yearsAgo: "anys enrere", yearAgo: "any enrere",
    today: "Avui", presentDay: "Actualitat · 2025",
    onTheMap: "Al mapa",
    map_region: "Terra poblada — color de la creença", map_route: "Ruta migratòria",
    map_settlement: "Poblament assolit", map_flow: "La creença s'escampa", map_pop: "Població (alçada)",
    hint: "Arrossega per girar · Roda per acostar · Arrossega la línia de temps",
    language: "Idioma",
    photos: "Fotos",
    gallery: "Galeria",
    tick_300ka: "300 ka", tick_ooa: "Fora d'Àfrica", tick_villages: "Primers llogarets",
    tick_cities: "Primeres ciutats", tick_2ka: "2 ka", tick_today: "Avui",
  },
  epochs: { palaeolithic: "Paleolític", neolithic: "Neolític", bronze: "Edat del bronze",
    iron: "Edat del ferro / clàssica", ce: "Era comuna" },
  era: { bce: "aC", ce: "dC" },
  story: [
    { k: "≈ Fa 300.000 anys · Àfrica", b: "Pren forma un nou tipus d'humà: l'Homo sapiens. No en un sol bressol, sinó arreu del continent alhora —l'origen panafricà—: una xarxa interconnectada de poblacions, del Marroc a Etiòpia i al Cap, que de mica en mica es fon en nosaltres." },
    { k: "El bressol africà", b: "Durant milers de generacions s'escampen sols pel continent —del Cap al Sàhara— dominant el foc, les eines i el llenguatge." },
    { k: "Fa ≈ 200.000 anys", b: "Enterren els seus morts, es pinten el cos amb ocre i comencen a percebre esperits en animals, rius i pedres: l'alba de l'animisme." },
    { k: "Primeres passes més enllà", b: "Petits grups vaguen al nord, cap al Llevant. Però el món fora d'Àfrica és dur, i aquestes primeres aventures s'esvaeixen." },
    { k: "Fa ≈ 70.000 anys · Fora d'Àfrica", b: "Per fi una petita població travessa l'estreta boca del mar Roig. Gairebé tothom que viu avui fora d'Àfrica descendeix d'aquest únic viatge." },
    { k: "El camí costaner", b: "Vorejant les costes d'Aràbia i de l'Índia, avancen cap a l'est a una velocitat sorprenent, vivint de les riqueses del mar." },
    { k: "Fa ≈ 55.000 anys · Sahul", b: "Travessant mar obert —els primers humans a fer-ho— arriben a Austràlia i es lliguen a la terra mitjançant tòtems i el Temps del Somni." },
    { k: "Fa ≈ 45.000 anys · Europa", b: "D'altres giren al nord, cap a l'Europa glacial. En la foscor de coves pintades, els xamans entren en trànsit per caminar entre els vius i el món dels esperits." },
    { k: "A través d'Àsia", b: "De les estepes occidentals al Pacífic, els humans omplen el vast cor d'Àsia, arribant a la Xina i a la vora del gel septentrional." },
    { k: "El nord glaçat", b: "En el moment més cru de la darrera glaciació, caçadors resistents s'endinsen a Sibèria, vestits amb pells cosides contra el fred mortal." },
    { k: "Fa ≈ 20.000 anys · Beríngia", b: "Tanta aigua queda atrapada en el gel que un pont de terra uneix Àsia amb Amèrica. Els caçadors el travessen cap a un Nou Món del tot buit." },
    { k: "Cap a les Amèriques", b: "D'Alaska als Andes, dos grans continents s'obren davant seu. Davallen pel Nou Món a una velocitat vertiginosa: la darrera gran massa de terra a sentir una petjada humana." },
    { k: "Fa ≈ 13.000 anys", b: "En uns pocs milers d'anys arriben a l'extrem sud d'Amèrica del Sud. La humanitat ja ha tocat tots els continents habitables." },
    { k: "La fi de la glaciació", b: "A mesura que el món s'escalfa, al Creixent Fèrtil la gent s'entreté vora camps de gra silvestre i comença, per primera vegada, a quedar-se en un lloc." },
    { k: "Fa ≈ 11.000 anys · Göbekli Tepe", b: "Abans de l'agricultura, abans de les ciutats, aixequen grans pilars tallats sobre els seus morts. Els avantpassats esdevenen guardians dels vius." },
    { k: "Els primers agricultors", b: "Es domestiquen el blat, l'ordi, les ovelles i el bestiar. Un camp conreat alimenta moltes més boques que la cacera, així que la gent deixa de vagar i s'estableix vora les collites. Arrelen els primers llogarets permanents." },
    { k: "Fa ≈ 3300 aC · Sumer", b: "El gra emmagatzemat alimenta ara els qui mai no conreen: escribes, sacerdots, soldats, reis. A Mesopotàmia, els llogarets crescuts esdevenen les primeres ciutats veritables, coronades per vastos panteons de déus." },
    { k: "Déus dels regnes fluvials", b: "Al llarg del Nil i de l'Indus, els temples esdevenen els motors de l'Estat, i un sacerdoci lletrat escriu al món la voluntat dels déus." },
    { k: "Fa ≈ 1350 aC · Egipte", b: "El faraó Akhenaton exalta un únic déu solar per damunt de tots els altres: un pas breu i radical cap a l'adoració d'un sol déu." },
    { k: "Fa ≈ 1000 aC · Pèrsia", b: "A l'Iran, el profeta Zaratustra replanteja el cosmos com una lluita entre el bé i el mal: un dualisme que ressonarà durant mil·lennis." },
    { k: "Fa ≈ 600 aC · Judà", b: "A l'exili de Babilònia, el poble de Judà declara el seu déu únic creador de totes les coses: el primer monoteisme durador." },
    { k: "Fa ≈ 500 aC · La Mediterrània", b: "Al voltant de la Mediterrània, Grècia i Roma fan dels seus déus ciutadans: patrons de ciutats, festes i jocs, venerats com a deure públic." },
    { k: "≈ segles I–IV dC · Cristianisme", b: "Des de la Mediterrània oriental, el cristianisme porta la idea d'un sol Déu pel món romà i, amb el temps, molt més enllà." },
    { k: "≈ segle VII dC · Islam", b: "A Aràbia sorgeix l'islam i s'escampa amb una rapidesa extraordinària: a l'oest cap a Espanya i pel Sàhara, i a l'est fins a l'Indus i la costa swahili." },
    { k: "El darrer gran viatge", b: "Lluny a l'est, als mars càlids del sud-est asiàtic insular, els millors navegants que mai han existit s'endinsen al Pacífic obert: comença la darrera gran migració humana." },
    { k: "Per l'oceà més remot", b: "Llegint l'onatge, els estels i els ocells, salten d'illa en illa a través de milers de milles de mar buit, poblant els darrers bocins de terra escampats de la Terra." },
    { k: "Aotearoa · la darrera terra", b: "El seu viatge final els porta al sud, cap a Nova Zelanda: la darrera gran massa de terra del planeta que els éssers humans assolirien." },
    { k: "≈ 1500 dC · Un món entrellaçat", b: "Els vaixells uneixen per fi els continents. Els europeus travessen els oceans oberts, i pobles, conreus i déus es mouen entre mons com mai abans; el cristianisme segueix l'imperi i el comerç cap a les Amèriques i per Àfrica." },
    { k: "Avui", b: "En tot just dos segles la humanitat salta de mil milions a vuit mil milions. Des d'un únic començament africà, la nostra espècie omple ara el planeta —cada continent habitable habitat—, portant tota la llarga herència de la creença, des dels primers esperits fins a una única deïtat exclusiva." },
  ],
  religions: {
    animism: { name: "Animisme", blurb: "La manera més antiga i estesa de veure el món: que tot —animals, rius, pedres, el temps, els morts— és viu, amb esperit i intenció. Més que una doctrina, és la postura humana per defecte davant d'un cosmos viu.", examples: "Caçadors-recol·lectors san del sud d'Àfrica · pobles amazònics · cultures circumpolars", when: "Des del Paleolític mitjà (~100.000 anys)" },
    shamanism: { name: "Xamanisme", blurb: "Especialistes —els xamans— entren en trànsit per viatjar entre el món humà i el dels esperits, guarint, endevinant i guiant la cacera. Les coves pintades de l'Europa glacial i de Sibèria en conserven algunes de les empremtes més antigues.", examples: "Pintors de Chauvet i Lascaux · pobles tungúsics de Sibèria (la paraula 'xaman' és evenki)", when: "Paleolític superior (~48.000 anys)" },
    totemism: { name: "Totemisme", blurb: "Els clans es lliguen a un tòtem —un animal, una planta, un lloc— que marca identitat, parentiu i obligació. A l'Austràlia aborigen, aquests lligams es teixeixen en el Temps del Somni, el paisatge etern dels éssers ancestrals.", examples: "Nacions aborígens australianes · molts sistemes de clans nord-americans i africans", when: "Viu a l'Austràlia aborigen (~50.000 anys)" },
    ancestor: { name: "Culte als avantpassats", blurb: "En establir-se en llogarets, els morts van quedar a prop. Els avantpassats esdevingueren guardians de la terra, el llinatge i la llei, honorats amb ofrenes, cranis tinguts i els primers santuaris monumentals.", examples: "Göbekli Tepe (~11.000 anys) · Çatalhöyük · ritus ancestrals xinesos posteriors", when: "Neolític (~12.000 anys)" },
    polytheism: { name: "Politeisme arcaic", blurb: "Les primeres ciutats necessitaven déus tan vasts i burocràtics com elles. Els panteons regien el cel, la tempesta, el gra i l'inframón; els temples esdevingueren els motors dels primers Estats, servits per un sacerdoci lletrat.", examples: "Sumer i Babilònia · Egipte · l'Indus i la Xina primerenca", when: "Edat del bronze (des de ~3200 aC)" },
    civic: { name: "Politeisme cívic", blurb: "A la Mediterrània clàssica, els déus esdevingueren també ciutadans: patrons de ciutats, festes i jocs. La religió era deure públic i identitat compartida tant com creença privada.", examples: "Ciutats-estat gregues · el culte estatal romà · tradicions vèdiques i després hindús", when: "Antiguitat clàssica (~900 aC – 400 dC)" },
    dualism: { name: "Dualisme", blurb: "El cosmos reformulat com un camp de batalla moral: un bé suprem enfrontat a un principi del mal, amb les decisions humanes decantant la balança. La visió de Zoroastre a Pèrsia ressonaria en fes posteriors.", examples: "Zoroastrisme a Pèrsia · després el maniqueisme", when: "Pèrsia de l'edat del ferro (~1000–700 aC)" },
    henotheism: { name: "Henoteisme i monolatria", blurb: "Un punt d'inflexió: es reconeixen molts déus, però un és exaltat per damunt de tots —o només ell mereix culte—. La breu revolució solar d'Akhenaton i la devoció del primer Israel a Jahvè marquen el camí cap a un sol Déu.", examples: "El culte a Aton d'Akhenaton (~1350 aC) · el jahvisme israelita primerenc", when: "Bronze tardà / ferro primerenc (~1400–600 aC)" },
    judaism: { name: "Judaisme", blurb: "Un sol Déu, creador de tot —sostingut de manera duradora per primera vegada pels judeus a l'Israel de l'edat del ferro i l'exili babilònic. L'arrel de la qual creixerien les altres fes abrahàmiques.", examples: "Israel i Judà · l'exili babilònic (~s. VI aC) · la diàspora jueva", when: "Des de l'edat del ferro (~600 aC)" },
    christianity: { name: "Cristianisme", blurb: "Nascut a la Judea romana, el cristianisme portà la idea d'un sol Déu per tot l'Imperi i, per convicció, conquesta i colònia, fins a Europa, les Amèriques i Àfrica: la fe més estesa de la Terra.", examples: "Imperi romà (~s. I dC) · l'Europa medieval · les Amèriques i Àfrica (des del s. XVI)", when: "Des del segle I dC" },
    islam: { name: "Islam", blurb: "Sorgit a l'Aràbia del segle VII, l'islam s'estengué amb una rapidesa extraordinària: a l'oest fins a la península Ibèrica, al sud pel Sàhara i la costa swahili, i a l'est fins a l'Indus i més enllà.", examples: "Aràbia (~s. VII dC) · els califats · el Sahel, la costa swahili i el sud d'Àsia", when: "Des del segle VII dC" },
  },
  chapters: [
    { t: "Una alba africana", b: "Fa uns 300.000 anys, a les sabanes i costes d'Àfrica, apareix un nou tipus d'humà: l'Homo sapiens. De complexió més lleugera i ment inquieta, s'escampa pel continent molt abans d'abandonar-lo." },
    { t: "Un continent explorat", b: "Durant més de cent mil·lennis, els humans moderns recorren Àfrica, perfeccionant eines, pigments i ornaments, i potser les primeres creences que el món és viu d'esperit." },
    { t: "Fora d'Àfrica", b: "Fa uns 70.000 anys una petita població travessa la boca del mar Roig cap a Aràbia. Tot no africà viu avui descendeix en gran part d'aquesta dispersió: un viatge que arribarà a tots els continents habitables." },
    { t: "Un món de caçadors", b: "Els humans irrompen a Austràlia, Europa i el cor d'Àsia. En coves pintades i en trànsit, els xamans uneixen els mons; els clans es lliguen a tòtems i a la terra." },
    { t: "El gel i el Nou Món", b: "A través de la darrera glaciació, els caçadors s'endinsen a Sibèria i travessen el pont de Beríngia cap a les Amèriques, corrent al sud fins a l'extrem del continent en uns pocs milers d'anys." },
    { t: "Els primers llogarets", b: "A mesura que el gel es retira, la gent s'estableix, conrea i construeix. Els morts romanen entre els vius com a avantpassats honorats; a Göbekli Tepe, s'aixequen monuments abans que ciutats." },
    { t: "Déus de les primeres ciutats", b: "A Mesopotàmia i Egipte, els primers Estats es coronen amb grans panteons. Els temples emmagatzemen gra i saber; un sacerdoci escriu al món la voluntat dels déus." },
    { t: "Una era de ferment", b: "De Pèrsia a la Mediterrània i a l'Índia, s'agiten noves visions: el dualisme còsmic, els déus cívics i l'audaç idea que un sol Déu podria estar per damunt de tots els altres, o en lloc seu." },
    { t: "Un Déu, molts pobles", b: "Portat per l'imperi, el comerç i la convicció, el monoteisme abrahàmic s'estén pels continents. Els descendents d'una única població africana omplen ara la Terra i porten amb si tota la llarga herència de la creença." },
  ],
  about: {
    open: "Quant a", close: "Tanca",
    title: "Quant a aquest atles",
    intro: "El Viatge Humà segueix la nostra espècie al llarg de 300.000 anys —des d'Àfrica fins a cada continent habitable— i traça, al costat d'aquesta gran migració, el desplegament de la creença humana, des de la primera intuïció d'esperits fins a les religions del món.",
    s: [
      { h: "Què estàs veient", b: "Un sol globus porta totes les capes alhora. La terra que brilla és terra poblada, tenyida amb el color de la creença que s'hi sosté. Les línies cian discontínues són rutes migratòries; els punts brillants marquen poblaments assolits. Els fluxos de color mostren creences que s'escampen d'un lloc a un altre, i les agulles rosades són la població: baixes en la prehistòria profunda, altíssimes a l'era de les ciutats. Els casquets blancs són el gel polar, que creix i recula amb les glaciacions." },
      { h: "Com navegar", b: "Prem Reproduir (o la barra espaiadora) per posar la història en marxa; la càmera, els rètols i la línia de temps es mouen junts. Fes servir les tecles ← i → per avançar fotograma a fotograma (o Maj + ← i → per a salts més ràpids), o arrossega la línia de temps per viatjar lliurement. Arrossega el globus per girar-lo i fes servir la roda per acostar. Fes clic en qualsevol creença del tauler Formes de creença per llegir-ne i centrar la vista; els taulers Capes del mapa i Tipus de globus permeten mostrar, amagar i reestilitzar cada element." },
      { h: "Com a eina docent", b: "Atura't en qualsevol moment per comentar-lo. Segueix com l'entorn modela la migració, i com el poblament, l'agricultura, les ciutats i la creença s'enlairen junts. Alterna les capes per aïllar un sol fil —només migració, o només religió— i canvia el gràfic de població entre lineal i logarítmic per mostrar com de recent és l'explosió del nostre nombre. Els rètols es llegeixen com un guió narrat per a una classe." },
      { h: "Per què el vam fer", b: "No per discutir, sinó per meravellar-nos. Aquest atles es va crear perquè qualsevol pugui aturar-se i contemplar el llarg i improbable arc dels orígens humans: un inquiet començament africà que, al llarg de deu mil generacions, va arribar a omplir la Terra sencera i a meravellar-se'n." },
    ],
    learnMore: {
      h: "Més informació",
      b: "Aquest atles és una síntesi, no una font. Per aprofundir en la migració, la genètica i la història de la creença, aquests són bons punts de partida:",
      links: [
        { label: "Smithsonian — What Does It Mean to Be Human?", url: "https://humanorigins.si.edu/", note: "evolució i orígens humans" },
        { label: "Bradshaw Foundation — The Journey of Mankind", url: "https://www.bradshawfoundation.com/journey/", note: "mapa genètic de la migració" },
        { label: "Our World in Data — Population Growth", url: "https://ourworldindata.org/population-growth", note: "la llarga corba demogràfica" },
        { label: "Britannica — The Study of Religion", url: "https://www.britannica.com/topic/study-of-religion", note: "la història de la creença" },
        { label: "Y. N. Harari — Sapiens", url: "https://www.ynharari.com/book/sapiens-2/", note: "una breu història de la humanitat" },
      ],
    },
  },
};
