/* Norsk (bokmål) — The Human Journey */
window.I18N.no = {
  places: {
      "origin": "Øst-Afrika",
      "origin_n": "Nord-Afrika",
      "south_afr": "Sørlige Afrika",
      "west_afr": "Vest-Afrika",
      "levant1": "Levanten (tidlig)",
      "levant2": "Levanten (tidlig)",
      "arabia": "Arabia",
      "south_asia": "Sør-Asia",
      "sahul": "Sahul (Australia)",
      "se_asia": "Sørøst-Asia",
      "europe": "Europa",
      "c_asia": "Sentral-Asia",
      "e_asia": "Øst-Asia",
      "siberia": "Sibir",
      "beringia": "Beringia",
      "n_america": "Nord-Amerika",
      "s_america": "Sør-Amerika",
      "patagonia": "Patagonia og det fjerne sør",
      "remote_oc": "Det fjerne Stillehavet",
      "nz": "Aotearoa (New Zealand)"
  },
  ui: {
    eyebrow: "Et interaktivt atlas",
    explore: "Utforsk", youAreHere: "Du er her",
    nav_globe: "Den menneskelige reisen", nav_globe_note: "Ut av Afrika — atlaset",
    nav_freedom: "Makt og frihet", nav_freedom_note: "Del VI · teorien om frihet",
    nav_origins: "Maktens opphav", nav_origins_note: "Del I · mekanismene",
    nav_iq: "Makt, rikdom og ulikhet", nav_iq_note: "Del II · mengdene",
    nav_cast: "Rollebesetningen og maskinen", nav_cast_note: "Del III · roller og staten",
    titleA: "Den Menneskelige", titleB: "Reisen",
    credit1: "Ut av Afrika", credit2: "og troens opphav",
    mapLayers: "Kartlag",
    layer_settlement: "Bosetning", layer_migration: "Migrasjon",
    layer_religion: "Religion", layer_population: "Befolkning", layer_ice: "Iskapper",
    globeType: "Globustype",
    theme_slate: "Skifer", theme_relief: "Relieff", theme_twilight: "Skumring", theme_atlas: "Atlas",
    formsOfBelief: "Trosformer", reset: "Tilbakestill",
    legItemTitle: "Klikk for å fokusere · Shift+klikk for å veksle",
    humanPopulation: "Verdens befolkning", humansAlive: "Mennesker i live",
    play: "Spill av", pause: "Pause",
    yearsAgo: "år siden", yearAgo: "år siden",
    today: "I dag", presentDay: "I dag · 2025",
    onTheMap: "På kartet",
    map_region: "Bosatt land — troens farge", map_route: "Migrasjonsrute",
    map_settlement: "Bosetning nådd", map_flow: "Troen sprer seg", map_pop: "Befolkning (høyde)",
    hint: "Dra for å rotere · Rull for å zoome · Dra tidslinjen",
    language: "Språk",
    photos: "Bilder",
    gallery: "Galleri",
    tick_300ka: "300 ka", tick_ooa: "Ut av Afrika", tick_villages: "Første landsbyer",
    tick_cities: "Første byer", tick_2ka: "2 ka", tick_today: "I dag",
  },
  epochs: { palaeolithic: "Paleolitikum", neolithic: "Neolitikum", bronze: "Bronsealder",
    iron: "Jernalder / antikken", ce: "Vår tidsregning" },
  era: { bce: "f.Kr.", ce: "e.Kr." },
  story: [
    { k: "≈ For 300 000 år siden · Afrika", b: "En ny slags menneske tar form — Homo sapiens. Ikke i én vugge, men over hele kontinentet på en gang — det panafrikanske opphavet: et sammenkoblet nett av befolkninger, fra Marokko til Etiopia til Kapp, som sakte smelter sammen til oss." },
    { k: "Det afrikanske opphavet", b: "I tusenvis av generasjoner sprer de seg alene over kontinentet — fra Kapp til Sahara — og mestrer ild, redskaper og språk." },
    { k: "≈ 200 000 år siden", b: "De begraver sine døde, maler kroppene med oker og begynner å ane ånder i dyr, elver og stein — animismens demring." },
    { k: "Første skritt utenfor", b: "Små flokker vandrer nordover til Levanten. Men verden utenfor Afrika er hard, og disse første forsøkene dør ut." },
    { k: "≈ 70 000 år siden · Ut av Afrika", b: "Endelig krysser en liten befolkning den trange munningen av Rødehavet. Nesten alle som lever utenfor Afrika i dag, stammer fra denne ene reisen." },
    { k: "Kystveien", b: "Langs kystene av Arabia og India beveger de seg østover med forbløffende fart, og lever av havets rikdom." },
    { k: "≈ 55 000 år siden · Sahul", b: "Over åpent hav — de første mennesker noensinne — når de Australia og binder seg til landet gjennom totemer og Drømmetiden." },
    { k: "≈ 45 000 år siden · Europa", b: "Andre vender nordover, til istidens Europa. I mørket i malte huler går sjamaner i transe for å vandre mellom de levende og åndeverdenen." },
    { k: "Tvers gjennom Asia", b: "Fra de vestlige steppene til Stillehavet fyller mennesker Asias veldige hjerte, helt til Kina og kanten av den nordlige isen." },
    { k: "Det frosne nord", b: "Gjennom det dypeste av siste istid trenger seige jegere inn i Sibir, kledd i sydde pelser mot den drepende kulden." },
    { k: "≈ 20 000 år siden · Beringia", b: "Så mye vann er bundet i is at en landbro forener Asia med Amerika. Jegere går over til en fullstendig tom Ny verden." },
    { k: "Inn i Amerika", b: "Fra Alaska til Andesfjellene åpner to store kontinenter seg for dem. De brer seg ned gjennom Den nye verden med svimlende fart — den siste store landmassen som kjenner et menneskelig fotavtrykk." },
    { k: "≈ 13 000 år siden", b: "I løpet av noen få tusen år når de sørspissen av Sør-Amerika. Menneskeheten har nå berørt hvert beboelig kontinent." },
    { k: "Istidens slutt", b: "Mens verden varmes opp, blir folk i Den fruktbare halvmåne værende ved åkrer med vill korn — og begynner, for første gang, å bli værende på ett sted." },
    { k: "≈ 11 000 år siden · Göbekli Tepe", b: "Før jordbruket, før byene, reiser de store uthugde steiner over sine døde. Forfedrene blir de levendes voktere." },
    { k: "De første bøndene", b: "Hvete, bygg, sau og storfe temmes. En dyrket åker metter langt flere munner enn jakten — så folk slutter å vandre og slår seg ned ved avlingene sine. De første varige landsbyene slår rot." },
    { k: "≈ 3300 f.Kr. · Sumer", b: "Lagret korn metter nå dem som aldri dyrker: skrivere, prester, soldater, konger. I Mesopotamia blir de oppsvulmede landsbyene de første ekte byene, kronet med veldige gudepanteoner." },
    { k: "Elvekongedømmenes guder", b: "Langs Nilen og Indus blir templene statens motorer, og et skriftkyndig presteskap skriver gudenes vilje inn i verden." },
    { k: "≈ 1350 f.Kr. · Egypt", b: "Faraoen Akhenaton opphøyer én solgud over alle andre — et kort, radikalt skritt mot å tilbe én gud alene." },
    { k: "≈ 1000 f.Kr. · Persia", b: "I Iran omformer profeten Zarathustra kosmos til en kamp mellom godt og ondt — en dualisme som vil gi gjenklang i årtusener." },
    { k: "≈ 600 f.Kr. · Juda", b: "I eksil i Babylon erklærer Judas folk sin gud som den ene skaper av alle ting — den første varige monoteismen." },
    { k: "≈ 500 f.Kr. · Middelhavet", b: "Rundt Middelhavet gjør Hellas og Roma sine guder til borgere — vernere av byer, fester og leker, dyrket som offentlig plikt." },
    { k: "≈ 1.–4. årh. e.Kr. · Kristendom", b: "Fra det østlige Middelhavet bærer kristendommen ideen om én Gud gjennom den romerske verden — og med tiden langt utover den." },
    { k: "≈ 600-tallet e.Kr. · Islam", b: "I Arabia oppstår islam og sprer seg med usedvanlig fart — vestover til Spania og over Sahara, og østover til Indus og swahilikysten." },
    { k: "Den siste store sjøreisen", b: "Langt mot øst, i de varme havene i det insulære Sørøst-Asia, legger de fineste navigatører som noen gang har levd, ut på det åpne Stillehavet: den siste store menneskelige migrasjonen begynner." },
    { k: "Over det fjerneste hav", b: "De leser dønning, stjerne og fugl, og hopper fra øy til øy over tusenvis av mil med tomt hav, og bosetter de siste spredte flekkene av land på jorden." },
    { k: "Aotearoa · det siste landet", b: "Deres siste reise fører dem sørover til New Zealand — den siste store landmassen på jorden som mennesker noensinne ville nå." },
    { k: "≈ 1500 e.Kr. · En sammenvevd verden", b: "Skip binder endelig kontinentene sammen. Europeere krysser de åpne havene, og folk, vekster og guder beveger seg mellom verdener som aldri før — kristendommen følger imperium og handel til Amerika og over Afrika." },
    { k: "I dag", b: "På knapt to århundrer stiger menneskeheten fra én til åtte milliarder. Fra én enkelt afrikansk begynnelse fyller arten vår nå planeten — hvert beboelig kontinent bebodd — og bærer hele den lange trosarven, fra de første åndene til én eksklusiv guddom." },
  ],
  religions: {
    animism: { name: "Animisme", blurb: "Den eldste og mest utbredte måten å se verden på: at alt — dyr, elver, steiner, været, de døde — er levende, med ånd og hensikt. Mindre en lære enn menneskets grunnholdning til et levende kosmos.", examples: "San-jeger-sankere i det sørlige Afrika · amazonfolk · sirkumpolare kulturer", when: "Fra mellompaleolitikum (~100 000 år)" },
    shamanism: { name: "Sjamanisme", blurb: "Spesialister — sjamaner — går i transe for å reise mellom menneske- og åndeverdenen, helbredende, spående og ledende jakten. De malte hulene i istidens Europa og Sibir bevarer noen av dens eldste spor.", examples: "Hulemalerne i Chauvet og Lascaux · tungusiske folk i Sibir (ordet «sjaman» er evenkisk)", when: "Yngre paleolitikum (~48 000 år)" },
    totemism: { name: "Totemisme", blurb: "Klaner binder seg til et totem — et dyr, en plante eller et sted — som markerer identitet, slektskap og forpliktelse. I aboriginenes Australia er disse båndene vevd inn i Drømmetiden, forfedrevesenenes evige landskap.", examples: "Aboriginske nasjoner i Australia · mange nordamerikanske og afrikanske klansystemer", when: "Levende i aboriginenes Australia (~50 000 år)" },
    ancestor: { name: "Forfedredyrkelse", blurb: "Da folk slo seg ned i landsbyer, ble de døde værende nær. Forfedrene ble voktere av land, ætt og lov, æret med offer, stelte hodeskaller og de første monumentale helligdommene.", examples: "Göbekli Tepe (~11 000 år) · Çatalhöyük · senere kinesiske forfedreritualer", when: "Neolitikum (~12 000 år)" },
    polytheism: { name: "Arkaisk polyteisme", blurb: "De første byene trengte guder like veldige og byråkratiske som dem selv. Panteoner rådde over himmel, storm, korn og dødsrike; templene ble de tidligste statenes motorer, tjent av et skriftkyndig presteskap.", examples: "Sumer og Babylon · Egypt · Indus og det tidlige Kina", when: "Bronsealder (fra ~3200 f.Kr.)" },
    civic: { name: "Borgerlig polyteisme", blurb: "I det klassiske Middelhavet ble gudene også borgere: vernere av byer, fester og leker. Religion var offentlig plikt og felles identitet like mye som privat tro.", examples: "Greske bystater · den romerske statskulten · vediske og senere hinduistiske tradisjoner", when: "Klassisk antikk (~900 f.Kr. – 400 e.Kr.)" },
    dualism: { name: "Dualisme", blurb: "Kosmos omtenkt som en moralsk slagmark: et høyeste gode i kamp med et ondskapens prinsipp, der menneskets valg vipper vektskålen. Zarathustras visjon i Persia ville gi gjenklang i senere trosretninger.", examples: "Zoroastrisme i Persia · senere manikeisme", when: "Jernalderens Persia (~1000–700 f.Kr.)" },
    henotheism: { name: "Henoteisme og monolatri", blurb: "Et vendepunkt: mange guder anerkjennes, men én opphøyes over alle — eller alene fortjener dyrkelse. Akhenatons korte solrevolusjon og det tidlige Israels hengivenhet til Jahve staker ut veien mot én Gud.", examples: "Akhenatons Aton-kult (~1350 f.Kr.) · tidlig israelittisk jahvisme", when: "Sen bronsealder / tidlig jernalder (~1400–600 f.Kr.)" },
    judaism: { name: "Jødedom", blurb: "Én Gud, skaper av alt — for første gang varig holdt av judeerne i jernalderens Israel og det babylonske eksilet. Roten som de andre abrahamittiske trosretningene ville vokse ut av.", examples: "Israel og Juda · det babylonske eksilet (~500-tallet f.Kr.) · den jødiske diasporaen", when: "Fra jernalderen (~600 f.Kr.)" },
    christianity: { name: "Kristendom", blurb: "Født i det romerske Judea bar kristendommen ideen om én Gud gjennom Riket og, ved overbevisning, erobring og koloni, til Europa, Amerika og Afrika: jordens mest utbredte tro.", examples: "Romerriket (~1. årh. e.Kr.) · middelalderens Europa · Amerika og Afrika (fra 1500-tallet)", when: "Fra 1. århundre e.Kr." },
    islam: { name: "Islam", blurb: "Oppstått i 600-tallets Arabia spredte islam seg med usedvanlig fart — vestover til Den iberiske halvøy, sørover over Sahara og swahilikysten, og østover til Indus og videre.", examples: "Arabia (~600-tallet e.Kr.) · kalifatene · Sahel, swahilikysten og Sør-Asia", when: "Fra 600-tallet e.Kr." },
  },
  chapters: [
    { t: "En afrikansk daggry", b: "For rundt 300 000 år siden, på Afrikas savanner og kyster, dukker en ny slags menneske opp: Homo sapiens. Lettere bygd og rastløs av sinn brer det seg over kontinentet lenge før det forlater det." },
    { t: "Et utforsket kontinent", b: "I mer enn hundre årtusener streifer moderne mennesker Afrika, foredler redskaper, pigmenter og pynt, og kanskje de første forestillingene om at verden er levende av ånd." },
    { t: "Ut av Afrika", b: "For rundt 70 000 år siden krysser en liten befolkning Rødehavets munning til Arabia. Enhver ikke-afrikaner som lever i dag, stammer i stor grad fra denne spredningen: en reise som vil nå hvert beboelig kontinent." },
    { t: "En jegerverden", b: "Mennesker velter inn i Australia, Europa og Asias hjerte. I malte huler og i transe bygger sjamaner bro mellom verdenene; klaner binder seg til totemer og til landet." },
    { t: "Isen og Den nye verden", b: "Gjennom siste istid trenger jegere inn i Sibir og krysser Beringia-landbroen til Amerika, og iler sørover til kontinentets spiss i løpet av noen få tusen år." },
    { t: "De første landsbyene", b: "Mens isen trekker seg tilbake, slår folk seg ned, dyrker og bygger. De døde blir værende blant de levende som ærede forfedre; i Göbekli Tepe reiser mennesker monumenter før de reiser byer." },
    { t: "De første byenes guder", b: "I Mesopotamia og Egypt kroner de første statene seg med store panteoner. Templene lagrer korn og kunnskap; et presteskap skriver gudenes vilje inn i verden." },
    { t: "En gjæringens tid", b: "Fra Persia til Middelhavet og India rører nye visjoner seg — kosmisk dualisme, borgerlige guder, og den dristige tanken at én Gud kunne stå over alle andre, eller i deres sted." },
    { t: "Én Gud, mange folk", b: "Båret av imperium, handel og overbevisning sprer den abrahamittiske monoteismen seg over kontinentene. Etterkommerne av én enkelt afrikansk befolkning fyller nå jorden — og bærer med seg hele den lange trosarven." },
  ],
  about: {
    open: "Om", close: "Lukk",
    title: "Om dette atlaset",
    intro: "Den Menneskelige Reisen følger arten vår gjennom 300 000 år — ut av Afrika til hvert beboelig kontinent — og sporer, ved siden av den store migrasjonen, utffoldelsen av menneskelig tro, fra den første anelsen om ånder til verdensreligionene.",
    s: [
      { h: "Hva du ser", b: "Én enkelt globus bærer alle lag på en gang. Lysende land er bosatt land, tonet med fargen til troen som holdes der. Stiplede cyan-linjer er migrasjonsruter; lyse prikker markerer bosetninger som er nådd. Fargede strømmer viser tro som sprer seg fra sted til sted, og de rosa spirene er befolkning — lave i den dype forhistorien, ruvende i byenes tid. Hvite kapper er polarisen, som svulmer og trekker seg tilbake med istidene." },
      { h: "Slik navigerer du", b: "Trykk Spill av (eller mellomromstasten) for å sette historien i bevegelse; kamera, tekster og tidslinje beveger seg sammen. Bruk ← og → for å gå bilde for bilde (eller Shift + ← og → for raskere hopp), eller dra tidslinjen for å reise fritt. Dra globusen for å rotere den og rull for å zoome. Klikk på en tro i panelet Trosformer for å lese om den og sentrere blikket; panelene Kartlag og Globustype lar deg vise, skjule og stilsette hvert element." },
      { h: "Som læringsverktøy", b: "Sett på pause når som helst for å drøfte det. Følg hvordan miljøet former migrasjon, og hvordan bosetning, jordbruk, byer og tro stiger sammen. Veksle lagene for å isolere én enkelt tråd — bare migrasjon, eller bare religion — og bytt befolkningsgrafen mellom lineær og logaritmisk for å vise hvor nylig tallene våre eksploderte. Tekstene leses som et fortalt manus for en klasse." },
      { h: "Hvorfor vi laget det", b: "Ikke for å argumentere, men for å undres. Dette atlaset ble bygd for at hvem som helst skal kunne tre tilbake og ta inn den lange, usannsynlige buen av menneskets opphav — én rastløs afrikansk begynnelse som, gjennom ti tusen generasjoner, kom til å fylle hele jorden og undre seg over den." },
    ],
    learnMore: {
      h: "Lær mer",
      b: "Dette atlaset er en syntese, ikke en kilde. For å gå dypere inn i migrasjonen, genetikken og troens historie er dette gode steder å begynne:",
      links: [
        { label: "Smithsonian — What Does It Mean to Be Human?", url: "https://humanorigins.si.edu/", note: "menneskelig evolusjon og opphav" },
        { label: "Bradshaw Foundation — The Journey of Mankind", url: "https://www.bradshawfoundation.com/journey/", note: "genetisk kart over migrasjonen" },
        { label: "Our World in Data — Population Growth", url: "https://ourworldindata.org/population-growth", note: "den lange befolkningskurven" },
        { label: "Britannica — The Study of Religion", url: "https://www.britannica.com/topic/study-of-religion", note: "troens historie" },
        { label: "Y. N. Harari — Sapiens", url: "https://www.ynharari.com/book/sapiens-2/", note: "en kort historie om menneskeheten" },
      ],
    },
  },
};
