/* Español — The Human Journey */
window.I18N.es = {
  places: {
      "origin": "África Oriental",
      "origin_n": "África del Norte",
      "south_afr": "África Austral",
      "west_afr": "África Occidental",
      "levant1": "El Levante (inicios)",
      "levant2": "El Levante (inicios)",
      "arabia": "Arabia",
      "south_asia": "Asia Meridional",
      "sahul": "Sahul (Australia)",
      "se_asia": "Sudeste Asiático",
      "europe": "Europa",
      "c_asia": "Asia Central",
      "e_asia": "Asia Oriental",
      "siberia": "Siberia",
      "beringia": "Beringia",
      "n_america": "América del Norte",
      "s_america": "América del Sur",
      "patagonia": "Patagonia y el extremo sur",
      "remote_oc": "Pacífico remoto",
      "nz": "Aotearoa (Nueva Zelanda)"
  },
  ui: {
    eyebrow: "Un atlas interactivo",
    titleA: "El Viaje", titleB: "Humano",
    credit1: "Fuera de África", credit2: "y los orígenes de la creencia",
    mapLayers: "Capas del mapa",
    layer_settlement: "Asentamiento", layer_migration: "Migración",
    layer_religion: "Religión", layer_population: "Población", layer_ice: "Casquetes de hielo",
    globeType: "Tipo de globo",
    theme_slate: "Pizarra", theme_relief: "Relieve", theme_twilight: "Crepúsculo", theme_atlas: "Atlas",
    formsOfBelief: "Formas de creencia", reset: "Reiniciar",
    legItemTitle: "Clic para enfocar · Mayús+clic para alternar",
    humanPopulation: "Población humana", humansAlive: "Humanos vivos",
    play: "Reproducir", pause: "Pausar",
    yearsAgo: "años atrás", yearAgo: "año atrás",
    today: "Hoy", presentDay: "Actualidad · 2025",
    onTheMap: "En el mapa",
    map_region: "Tierra poblada — color de la creencia", map_route: "Ruta migratoria",
    map_settlement: "Asentamiento alcanzado", map_flow: "La creencia se difunde", map_pop: "Población (altura)",
    hint: "Arrastra para girar · Rueda para acercar · Arrastra la línea de tiempo",
    language: "Idioma",
    photos: "Fotos",
    gallery: "Galería",
    tick_300ka: "300 ka", tick_ooa: "Fuera de África", tick_villages: "Primeras aldeas",
    tick_cities: "Primeras ciudades", tick_2ka: "2 ka", tick_today: "Hoy",
  },
  epochs: { palaeolithic: "Paleolítico", neolithic: "Neolítico", bronze: "Edad del Bronce",
    iron: "Edad del Hierro / clásica", ce: "Era común" },
  era: { bce: "a. C.", ce: "d. C." },
  story: [
    { k: "≈ Hace 300 000 años · África", b: "Toma forma un nuevo tipo de humano: el Homo sapiens. No en una sola cuna, sino en todo el continente a la vez —el origen panafricano—: una red interconectada de poblaciones, de Marruecos a Etiopía y al Cabo, que poco a poco se funde en nosotros." },
    { k: "La cuna africana", b: "Durante miles de generaciones se extienden solos por el continente —del Cabo al Sáhara— dominando el fuego, las herramientas y el lenguaje." },
    { k: "Hace ≈ 200 000 años", b: "Entierran a sus muertos, pintan sus cuerpos con ocre y empiezan a percibir espíritus en animales, ríos y piedras: el amanecer del animismo." },
    { k: "Primeros pasos más allá", b: "Pequeños grupos vagan al norte, hacia el Levante. Pero el mundo fuera de África es duro, y estas primeras aventuras se desvanecen." },
    { k: "Hace ≈ 70 000 años · Fuera de África", b: "Por fin una pequeña población cruza la estrecha boca del mar Rojo. Casi todos los que viven hoy fuera de África descienden de este único viaje." },
    { k: "El camino costero", b: "Bordeando las costas de Arabia y la India, avanzan al este a una velocidad asombrosa, viviendo de las riquezas del mar." },
    { k: "Hace ≈ 55 000 años · Sahul", b: "Cruzando mar abierto —los primeros humanos en hacerlo— llegan a Australia y se ligan a la tierra mediante tótems y el Tiempo del Sueño." },
    { k: "Hace ≈ 45 000 años · Europa", b: "Otros giran al norte, hacia la Europa glacial. En la oscuridad de cuevas pintadas, los chamanes entran en trance para caminar entre los vivos y el mundo de los espíritus." },
    { k: "A través de Asia", b: "De las estepas occidentales al Pacífico, los humanos llenan el vasto corazón de Asia, alcanzando China y el borde del hielo septentrional." },
    { k: "El norte helado", b: "En lo más crudo de la última Edad de Hielo, cazadores resistentes penetran en Siberia, vestidos con pieles cosidas contra el frío mortal." },
    { k: "Hace ≈ 20 000 años · Beringia", b: "Tanta agua queda atrapada en el hielo que un puente de tierra une Asia con América. Los cazadores cruzan a un Nuevo Mundo enteramente vacío." },
    { k: "Hacia las Américas", b: "De Alaska a los Andes, dos grandes continentes se abren ante ellos. Descienden por el Nuevo Mundo a velocidad vertiginosa: la última gran masa de tierra en sentir una huella humana." },
    { k: "Hace ≈ 13 000 años", b: "En unos pocos miles de años alcanzan el extremo sur de Sudamérica. La humanidad ha tocado ya todos los continentes habitables." },
    { k: "El fin de la Edad de Hielo", b: "A medida que el mundo se calienta, en el Creciente Fértil la gente se demora junto a campos de grano silvestre y empieza, por primera vez, a quedarse en un lugar." },
    { k: "Hace ≈ 11 000 años · Göbekli Tepe", b: "Antes de la agricultura, antes de las ciudades, levantan grandes pilares tallados sobre sus muertos. Los antepasados se vuelven guardianes de los vivos." },
    { k: "Los primeros agricultores", b: "Se domestican el trigo, la cebada, las ovejas y el ganado. Un campo cultivado alimenta muchas más bocas que la caza, así que la gente deja de vagar y se asienta junto a sus cosechas. Arraigan las primeras aldeas permanentes." },
    { k: "Hace ≈ 3300 a. C. · Sumer", b: "El grano almacenado alimenta ahora a quienes nunca cultivan: escribas, sacerdotes, soldados, reyes. En Mesopotamia, las aldeas crecidas se convierten en las primeras ciudades verdaderas, coronadas por vastos panteones de dioses." },
    { k: "Dioses de los reinos fluviales", b: "A lo largo del Nilo y el Indo, los templos se vuelven los motores del Estado, y un sacerdocio letrado escribe en el mundo la voluntad de los dioses." },
    { k: "Hace ≈ 1350 a. C. · Egipto", b: "El faraón Akhenatón exalta a un único dios solar por encima de todos los demás: un paso breve y radical hacia la adoración de un solo dios." },
    { k: "Hace ≈ 1000 a. C. · Persia", b: "En Irán, el profeta Zaratustra replantea el cosmos como una lucha entre el bien y el mal: un dualismo que resonará durante milenios." },
    { k: "Hace ≈ 600 a. C. · Judá", b: "En el exilio de Babilonia, el pueblo de Judá declara a su dios único creador de todas las cosas: el primer monoteísmo duradero." },
    { k: "Hace ≈ 500 a. C. · El Mediterráneo", b: "En torno al Mediterráneo, Grecia y Roma hacen de sus dioses ciudadanos: patronos de ciudades, fiestas y juegos, venerados como deber público." },
    { k: "≈ siglos I–IV d. C. · Cristianismo", b: "Desde el Mediterráneo oriental, el cristianismo lleva la idea de un solo Dios por el mundo romano y, con el tiempo, mucho más allá." },
    { k: "≈ siglo VII d. C. · Islam", b: "En Arabia surge el islam y se extiende con extraordinaria rapidez: al oeste hacia España y por el Sáhara, y al este hasta el Indo y la costa swahili." },
    { k: "El último gran viaje", b: "Lejos al este, en los cálidos mares del sudeste asiático insular, los mejores navegantes que jamás existieron se lanzan al Pacífico abierto: comienza la última gran migración humana." },
    { k: "Por el océano más remoto", b: "Leyendo el oleaje, las estrellas y las aves, saltan de isla en isla a través de miles de millas de mar vacío, poblando los últimos retazos de tierra de la Tierra." },
    { k: "Aotearoa · la última tierra", b: "Su viaje final los lleva al sur, a Nueva Zelanda: la última gran masa de tierra del planeta que los seres humanos alcanzarían." },
    { k: "≈ 1500 d. C. · Un mundo entrelazado", b: "Los barcos unen al fin los continentes. Los europeos cruzan los océanos abiertos, y pueblos, cultivos y dioses se mueven entre mundos como nunca antes; el cristianismo sigue al imperio y al comercio hacia las Américas y por África." },
    { k: "Hoy", b: "En apenas dos siglos la humanidad salta de mil millones a ocho mil millones. Desde un único comienzo africano, nuestra especie llena ahora el planeta —cada continente habitable habitado—, portando toda la larga herencia de la creencia, desde los primeros espíritus hasta una única deidad exclusiva." },
  ],
  religions: {
    animism: { name: "Animismo", blurb: "La forma más antigua y extendida de ver el mundo: que todo —animales, ríos, piedras, el clima, los muertos— está vivo, con espíritu e intención. Más que una doctrina, es la postura humana por defecto ante un cosmos vivo.", examples: "Cazadores-recolectores san del sur de África · pueblos amazónicos · culturas circumpolares", when: "Desde el Paleolítico Medio (~100 000 años)" },
    shamanism: { name: "Chamanismo", blurb: "Especialistas —los chamanes— entran en trance para viajar entre el mundo humano y el de los espíritus, sanando, adivinando y guiando la caza. Las cuevas pintadas de la Europa glacial y de Siberia conservan algunas de sus huellas más antiguas.", examples: "Pintores de Chauvet y Lascaux · pueblos tungúsicos de Siberia (la palabra 'chamán' es evenki)", when: "Paleolítico Superior (~48 000 años)" },
    totemism: { name: "Totemismo", blurb: "Los clanes se ligan a un tótem —un animal, una planta, un lugar— que marca identidad, parentesco y obligación. En la Australia aborigen, estos vínculos se tejen en el Tiempo del Sueño, el paisaje eterno de los seres ancestrales.", examples: "Naciones aborígenes australianas · muchos sistemas de clanes norteamericanos y africanos", when: "Vívido en la Australia aborigen (~50 000 años)" },
    ancestor: { name: "Culto a los antepasados", blurb: "Al asentarse en aldeas, los muertos quedaron cerca. Los antepasados se volvieron guardianes de la tierra, el linaje y la ley, honrados con ofrendas, cráneos cuidados y los primeros santuarios monumentales.", examples: "Göbekli Tepe (~11 000 años) · Çatalhöyük · ritos ancestrales chinos posteriores", when: "Neolítico (~12 000 años)" },
    polytheism: { name: "Politeísmo arcaico", blurb: "Las primeras ciudades necesitaban dioses tan vastos y burocráticos como ellas. Los panteones regían el cielo, la tormenta, el grano y el inframundo; los templos se volvieron los motores de los primeros Estados, servidos por un sacerdocio letrado.", examples: "Sumer y Babilonia · Egipto · el Indo y la China temprana", when: "Edad del Bronce (desde ~3200 a. C.)" },
    civic: { name: "Politeísmo cívico", blurb: "En el Mediterráneo clásico, los dioses se volvieron también ciudadanos: patronos de ciudades, fiestas y juegos. La religión era deber público e identidad compartida tanto como creencia privada.", examples: "Ciudades-Estado griegas · el culto estatal romano · tradiciones védicas y luego hindúes", when: "Antigüedad clásica (~900 a. C. – 400 d. C.)" },
    dualism: { name: "Dualismo", blurb: "El cosmos reformulado como un campo de batalla moral: un bien supremo enfrentado a un principio del mal, con las decisiones humanas inclinando la balanza. La visión de Zoroastro en Persia resonaría en fes posteriores.", examples: "Zoroastrismo en Persia · luego el maniqueísmo", when: "Persia de la Edad del Hierro (~1000–700 a. C.)" },
    henotheism: { name: "Henoteísmo y monolatría", blurb: "Un punto de inflexión: se reconocen muchos dioses, pero uno es exaltado por encima de todos —o solo él merece culto—. La breve revolución solar de Akhenatón y la devoción del Israel temprano a Yahvé marcan el camino hacia un solo Dios.", examples: "El culto a Atón de Akhenatón (~1350 a. C.) · el yahvismo israelita temprano", when: "Bronce tardío / Hierro temprano (~1400–600 a. C.)" },
    judaism: { name: "Judaísmo", blurb: "Un solo Dios, creador de todo, sostenido de forma duradera por primera vez por los judeos en el Israel de la Edad del Hierro y el exilio babilónico. La raíz de la que crecerían las demás fes abrahámicas.", examples: "Israel y Judá · el exilio babilónico (~s. VI a. C.) · la diáspora judía", when: "Desde la Edad del Hierro (~600 a. C.)" },
    christianity: { name: "Cristianismo", blurb: "Nacido en la Judea romana, el cristianismo llevó la idea de un solo Dios por todo el Imperio y, por convicción, conquista y colonia, a Europa, las Américas y África: la fe más extendida de la Tierra.", examples: "Imperio romano (~s. I d. C.) · la Europa medieval · las Américas y África (desde el s. XVI)", when: "Desde el siglo I d. C." },
    islam: { name: "Islam", blurb: "Surgido en la Arabia del siglo VII, el islam se extendió con extraordinaria rapidez: al oeste hasta Iberia, al sur por el Sáhara y la costa swahili, y al este hasta el Indo y más allá.", examples: "Arabia (~s. VII d. C.) · los califatos · el Sahel, la costa swahili y el sur de Asia", when: "Desde el siglo VII d. C." },
  },
  chapters: [
    { t: "Un amanecer africano", b: "Hace unos 300 000 años, en las sabanas y costas de África, aparece un nuevo tipo de humano: el Homo sapiens. De complexión más ligera y mente inquieta, se extiende por el continente mucho antes de abandonarlo." },
    { t: "Un continente explorado", b: "Durante más de cien milenios, los humanos modernos recorren África, perfeccionando herramientas, pigmentos y adornos, y quizá las primeras creencias de que el mundo está vivo de espíritu." },
    { t: "Fuera de África", b: "Hace unos 70 000 años una pequeña población cruza la boca del mar Rojo hacia Arabia. Todo no africano vivo hoy desciende en gran parte de esta dispersión: un viaje que alcanzará todos los continentes habitables." },
    { t: "Un mundo de cazadores", b: "Los humanos irrumpen en Australia, Europa y el corazón de Asia. En cuevas pintadas y en trance, los chamanes tienden puentes entre los mundos; los clanes se ligan a tótems y a la tierra." },
    { t: "El hielo y el Nuevo Mundo", b: "A través de la última Edad de Hielo, los cazadores penetran en Siberia y cruzan el puente de tierra de Beringia hacia las Américas, corriendo al sur hasta el extremo del continente en unos pocos miles de años." },
    { t: "Las primeras aldeas", b: "Al retirarse el hielo, la gente se asienta, cultiva y construye. Los muertos permanecen entre los vivos como antepasados honrados; en Göbekli Tepe, los humanos levantan monumentos antes que ciudades." },
    { t: "Dioses de las primeras ciudades", b: "En Mesopotamia y Egipto, los primeros Estados se coronan con grandes panteones. Los templos almacenan grano y saber; un sacerdocio escribe en el mundo la voluntad de los dioses." },
    { t: "Una era de fermento", b: "De Persia al Mediterráneo y a la India, se agitan nuevas visiones: el dualismo cósmico, los dioses cívicos y la audaz idea de que un solo Dios podría estar por encima de todos los demás, o en su lugar." },
    { t: "Un Dios, muchos pueblos", b: "Llevado por el imperio, el comercio y la convicción, el monoteísmo abrahámico se extiende por los continentes. Los descendientes de una única población africana llenan ahora la Tierra y portan consigo toda la larga herencia de la creencia." },
  ],
  about: {
    open: "Acerca de", close: "Cerrar",
    title: "Acerca de este atlas",
    intro: "El Viaje Humano sigue a nuestra especie a lo largo de 300 000 años —desde África hasta cada continente habitable— y traza, junto a esa gran migración, el despliegue de la creencia humana, desde la primera intuición de espíritus hasta las religiones del mundo.",
    s: [
      { h: "Lo que estás viendo", b: "Un solo globo porta todas las capas a la vez. La tierra que brilla es tierra poblada, teñida con el color de la creencia que allí se sostiene. Las líneas cian discontinuas son rutas migratorias; los puntos brillantes marcan asentamientos alcanzados. Los flujos de color muestran creencias que se difunden de un lugar a otro, y las agujas rosadas son la población: bajas en la prehistoria profunda, altísimas en la era de las ciudades. Los casquetes blancos son el hielo polar, que crece y retrocede con las glaciaciones." },
      { h: "Cómo navegar", b: "Pulsa Reproducir (o la barra espaciadora) para poner la historia en marcha; la cámara, los rótulos y la línea de tiempo se mueven juntos. Usa las teclas ← y → para avanzar fotograma a fotograma (o Mayús + ← y → para saltos más rápidos), o arrastra la línea de tiempo para viajar libremente. Arrastra el globo para girarlo y usa la rueda para acercar. Haz clic en cualquier creencia del panel Formas de creencia para leer sobre ella y centrar la vista; los paneles Capas del mapa y Tipo de globo permiten mostrar, ocultar y reestilizar cada elemento." },
      { h: "Como herramienta docente", b: "Detente en cualquier momento para comentarlo. Sigue cómo el entorno moldea la migración, y cómo el asentamiento, la agricultura, las ciudades y la creencia ascienden juntos. Alterna las capas para aislar un solo hilo —solo migración, o solo religión— y cambia el gráfico de población entre lineal y logarítmico para mostrar lo reciente que es la explosión de nuestro número. Los rótulos sirven como guion narrado para una clase." },
      { h: "Por qué lo hicimos", b: "No para discutir, sino para maravillarnos. Este atlas se creó para que cualquiera pueda detenerse y contemplar el largo e improbable arco de los orígenes humanos: un inquieto comienzo africano que, a lo largo de diez mil generaciones, llegó a llenar la Tierra entera y a asombrarse de ella." },
    ],
    learnMore: {
      h: "Más información",
      b: "Este atlas es una síntesis, no una fuente. Para profundizar en la migración, la genética y la historia de la creencia, estos son buenos puntos de partida:",
      links: [
        { label: "Smithsonian — What Does It Mean to Be Human?", url: "https://humanorigins.si.edu/", note: "evolución y orígenes humanos" },
        { label: "Bradshaw Foundation — The Journey of Mankind", url: "https://www.bradshawfoundation.com/journey/", note: "mapa genético de la migración" },
        { label: "Our World in Data — Population Growth", url: "https://ourworldindata.org/population-growth", note: "la larga curva demográfica" },
        { label: "Britannica — The Study of Religion", url: "https://www.britannica.com/topic/study-of-religion", note: "la historia de la creencia" },
        { label: "Y. N. Harari — Sapiens", url: "https://www.ynharari.com/book/sapiens-2/", note: "una breve historia de la humanidad" },
      ],
    },
  },
};
