/* Nederlands — The Human Journey */
window.I18N.nl = {
  places: {
      "origin": "Oost-Afrika",
      "origin_n": "Noord-Afrika",
      "south_afr": "Zuidelijk Afrika",
      "west_afr": "West-Afrika",
      "levant1": "De Levant (begin)",
      "levant2": "De Levant (begin)",
      "arabia": "Arabië",
      "south_asia": "Zuid-Azië",
      "sahul": "Sahul (Australië)",
      "se_asia": "Zuidoost-Azië",
      "europe": "Europa",
      "c_asia": "Centraal-Azië",
      "e_asia": "Oost-Azië",
      "siberia": "Siberië",
      "beringia": "Beringia",
      "n_america": "Noord-Amerika",
      "s_america": "Zuid-Amerika",
      "patagonia": "Patagonië en het verre zuiden",
      "remote_oc": "Verre Stille Oceaan",
      "nz": "Aotearoa (Nieuw-Zeeland)"
  },
  ui: {
    eyebrow: "Een interactieve atlas",
    titleA: "De Menselijke", titleB: "Reis",
    credit1: "Uit Afrika", credit2: "& de oorsprong van geloof",
    mapLayers: "Kaartlagen",
    layer_settlement: "Bewoning", layer_migration: "Migratie",
    layer_religion: "Religie", layer_population: "Bevolking", layer_ice: "IJskappen",
    globeType: "Globetype",
    theme_slate: "Leisteen", theme_relief: "Reliëf", theme_twilight: "Schemering", theme_atlas: "Atlas",
    formsOfBelief: "Vormen van geloof", reset: "Herstel",
    legItemTitle: "Klik om te focussen · Shift+klik om te wisselen",
    humanPopulation: "Wereldbevolking", humansAlive: "Mensen in leven",
    play: "Afspelen", pause: "Pauze",
    yearsAgo: "jaar geleden", yearAgo: "jaar geleden",
    today: "Vandaag", presentDay: "Heden · 2025",
    onTheMap: "Op de kaart",
    map_region: "Bewoond land — kleur van geloof", map_route: "Migratieroute",
    map_settlement: "Bewoning bereikt", map_flow: "Geloof verspreidt zich", map_pop: "Bevolking (hoogte)",
    hint: "Sleep om te draaien · Scroll om te zoomen · Sleep de tijdlijn",
    language: "Taal",
    photos: "Foto's",
    gallery: "Galerij",
    tick_300ka: "300 ka", tick_ooa: "Uit Afrika", tick_villages: "Eerste dorpen",
    tick_cities: "Eerste steden", tick_2ka: "2 ka", tick_today: "Vandaag",
  },
  epochs: { palaeolithic: "Paleolithicum", neolithic: "Neolithicum", bronze: "Bronstijd",
    iron: "IJzertijd / klassieke oudheid", ce: "Onze jaartelling" },
  era: { bce: "v.Chr.", ce: "n.Chr." },
  story: [
    { k: "≈ 300.000 jaar geleden · Afrika", b: "Een nieuw soort mens krijgt vorm — Homo sapiens. Niet in één bakermat maar over het hele continent tegelijk — de pan-Afrikaanse oorsprong: een onderling verbonden web van populaties, van Marokko tot Ethiopië tot de Kaap, dat langzaam in ons samensmelt." },
    { k: "De Afrikaanse bakermat", b: "Duizenden generaties lang verspreiden ze zich alleen over het continent — van de Kaap tot de Sahara — en beheersen vuur, werktuigen en taal." },
    { k: "≈ 200.000 jaar geleden", b: "Ze begraven hun doden, beschilderen hun lichaam met oker en beginnen geesten te bespeuren in dieren, rivieren en steen — de dageraad van het animisme." },
    { k: "Eerste stappen daarbuiten", b: "Kleine groepen trekken noordwaarts, de Levant in. Maar de wereld buiten Afrika is hard, en deze eerste pogingen sterven uit." },
    { k: "≈ 70.000 jaar geleden · Uit Afrika", b: "Eindelijk steekt een kleine bevolking de smalle monding van de Rode Zee over. Vrijwel iedereen die nu buiten Afrika leeft, stamt af van deze ene tocht." },
    { k: "De kustweg", b: "Langs de kusten van Arabië en India trekken ze met verbluffende snelheid oostwaarts, levend van de rijkdom van de zee." },
    { k: "≈ 55.000 jaar geleden · Sahul", b: "Over open zee — de eerste mensen ooit — bereiken ze Australië en binden zich aan het land via totems en de Droomtijd." },
    { k: "≈ 45.000 jaar geleden · Europa", b: "Anderen wenden zich noordwaarts, naar het ijstijd-Europa. In het donker van beschilderde grotten gaan sjamanen in trance om te wandelen tussen de levenden en de geestenwereld." },
    { k: "Door Azië", b: "Van de westelijke steppen tot de Stille Oceaan vullen mensen het uitgestrekte hart van Azië, tot aan China en de rand van het noordelijke ijs." },
    { k: "Het bevroren noorden", b: "In het diepst van de laatste ijstijd dringen taaie jagers Siberië binnen, gekleed in genaaide pelzen tegen de dodelijke kou." },
    { k: "≈ 20.000 jaar geleden · Beringia", b: "Zo veel water ligt vast in ijs dat een landbrug Azië met Amerika verbindt. Jagers steken over naar een volkomen lege Nieuwe Wereld." },
    { k: "De Amerika's in", b: "Van Alaska tot de Andes openen twee grote continenten zich voor hen. Ze trekken met adembenemende snelheid door de Nieuwe Wereld — de laatste grote landmassa die een menselijke voetstap voelt." },
    { k: "≈ 13.000 jaar geleden", b: "Binnen enkele duizenden jaren bereiken ze de zuidpunt van Zuid-Amerika. De mensheid heeft nu elk bewoonbaar continent aangeraakt." },
    { k: "Het einde van de ijstijd", b: "Terwijl de wereld opwarmt, blijven mensen in de Vruchtbare Halvemaan dralen bij velden wilde granen — en beginnen ze, voor het eerst, op één plek te blijven." },
    { k: "≈ 11.000 jaar geleden · Göbekli Tepe", b: "Vóór de landbouw, vóór de steden, richten ze grote gebeeldhouwde pijlers op boven hun doden. De voorouders worden hoeders van de levenden." },
    { k: "De eerste boeren", b: "Tarwe, gerst, schapen en runderen worden getemd. Een bewerkt veld voedt veel meer monden dan de jacht — dus stoppen mensen met zwerven en vestigen zich bij hun gewassen. De eerste blijvende dorpen schieten wortel." },
    { k: "≈ 3300 v.Chr. · Sumer", b: "Opgeslagen graan voedt nu wie nooit boert: schrijvers, priesters, soldaten, koningen. In Mesopotamië worden de gezwollen dorpen de eerste echte steden, gekroond met uitgestrekte godenpantheons." },
    { k: "Goden van de rivierrijken", b: "Langs de Nijl en de Indus worden tempels de motoren van de staat, en een geletterd priesterschap schrijft de wil van de goden de wereld in." },
    { k: "≈ 1350 v.Chr. · Egypte", b: "De farao Achnaton verheft één zonnegod boven alle andere — een korte, radicale stap naar de verering van één god alleen." },
    { k: "≈ 1000 v.Chr. · Perzië", b: "In Iran herdenkt de profeet Zarathoestra de kosmos als een strijd tussen goed en kwaad — een dualisme dat millennia zal naklinken." },
    { k: "≈ 600 v.Chr. · Juda", b: "In ballingschap in Babylon verklaart het volk van Juda zijn god de ene schepper van alle dingen — het eerste blijvende monotheisme." },
    { k: "≈ 500 v.Chr. · De Middellandse Zee", b: "Rond de Middellandse Zee maken Griekenland en Rome van hun goden burgers — beschermheren van steden, feesten en spelen, vereerd als publieke plicht." },
    { k: "≈ 1e–4e eeuw n.Chr. · Christendom", b: "Vanuit het oostelijke Middellandse-Zeegebied draagt het christendom het idee van één God door de Romeinse wereld — en met de tijd ver daarbuiten." },
    { k: "≈ 7e eeuw n.Chr. · Islam", b: "In Arabië ontstaat de islam en verspreidt zich met buitengewone snelheid — westwaarts naar Spanje en over de Sahara, en oostwaarts tot de Indus en de Swahilikust." },
    { k: "De laatste grote zeereis", b: "Ver in het oosten, in de warme zeeën van insulair Zuidoost-Azië, varen de beste navigators ooit de open Stille Oceaan op: de laatste grote menselijke migratie begint." },
    { k: "Over de verste oceaan", b: "Deining, ster en vogel lezend, springen ze van eiland naar eiland over duizenden mijlen lege zee, en bevolken de laatste verspreide stukjes land op aarde." },
    { k: "Aotearoa · het laatste land", b: "Hun laatste reis voert hen zuidwaarts naar Nieuw-Zeeland — de laatste grote landmassa op aarde die mensen ooit zouden bereiken." },
    { k: "≈ 1500 n.Chr. · Een verweven wereld", b: "Schepen verbinden eindelijk de continenten. Europeanen steken de open oceanen over, en volkeren, gewassen en goden bewegen tussen werelden als nooit tevoren — het christendom volgt rijk en handel naar de Amerika's en door Afrika." },
    { k: "Vandaag", b: "In amper twee eeuwen springt de mensheid van één naar acht miljard. Vanuit één Afrikaans begin vult onze soort nu de planeet — elk bewoonbaar continent bewoond — en draagt de hele lange erfenis van geloof mee, van de eerste geesten tot één exclusieve godheid." },
  ],
  religions: {
    animism: { name: "Animisme", blurb: "De oudste en meest verbreide manier om de wereld te zien: dat alles — dieren, rivieren, stenen, het weer, de doden — leeft, met geest en bedoeling. Minder een leer dan de standaard menselijke houding tegenover een levende kosmos.", examples: "San-jager-verzamelaars van zuidelijk Afrika · Amazonevolkeren · circumpolaire culturen", when: "Vanaf het Midden-Paleolithicum (~100.000 jaar)" },
    shamanism: { name: "Sjamanisme", blurb: "Specialisten — sjamanen — gaan in trance om te reizen tussen de mensen- en de geestenwereld, genezend, voorspellend en de jacht leidend. De beschilderde grotten van ijstijd-Europa en Siberië bewaren enkele van de oudste sporen.", examples: "Schilders van Chauvet en Lascaux · Toengoezische volkeren van Siberië (het woord 'sjamaan' is Evenki)", when: "Boven-Paleolithicum (~48.000 jaar)" },
    totemism: { name: "Totemisme", blurb: "Clans binden zich aan een totem — een dier, plant of plaats — die identiteit, verwantschap en verplichting markeert. In Aboriginal-Australië zijn deze banden geweven in de Droomtijd, het eeuwige landschap van voorouderlijke wezens.", examples: "Aboriginal-naties van Australië · veel Noord-Amerikaanse en Afrikaanse clansystemen", when: "Levend in Aboriginal-Australië (~50.000 jaar)" },
    ancestor: { name: "Voorouderverering", blurb: "Toen mensen zich in dorpen vestigden, bleven de doden dichtbij. De voorouders werden hoeders van land, geslacht en wet, geëerd met offers, verzorgde schedels en de eerste monumentale heiligdommen.", examples: "Göbekli Tepe (~11.000 jaar) · Çatalhöyük · latere Chinese voorouderriten", when: "Neolithicum (~12.000 jaar)" },
    polytheism: { name: "Archaïsch polytheïsme", blurb: "De eerste steden hadden goden nodig die even uitgestrekt en bureaucratisch waren als zijzelf. Pantheons heersten over hemel, storm, graan en onderwereld; tempels werden de motoren van de vroegste staten, gediend door een geletterd priesterschap.", examples: "Sumer en Babylon · Egypte · de Indus en het vroege China", when: "Bronstijd (vanaf ~3200 v.Chr.)" },
    civic: { name: "Burgerlijk polytheïsme", blurb: "In de klassieke Middellandse Zee werden de goden ook burgers: beschermheren van steden, feesten en spelen. Religie was publieke plicht en gedeelde identiteit, evenzeer als privégeloof.", examples: "Griekse stadstaten · de Romeinse staatscultus · Vedische en later hindoeïstische tradities", when: "Klassieke oudheid (~900 v.Chr. – 400 n.Chr.)" },
    dualism: { name: "Dualisme", blurb: "De kosmos herdacht als een moreel slagveld: een hoogste goed in strijd met een beginsel van het kwaad, waarbij menselijke keuzes de balans doen doorslaan. Zarathoestra's visioen in Perzië zou naklinken in latere geloven.", examples: "Zoroastrisme in Perzië · later het manicheïsme", when: "IJzertijd-Perzië (~1000–700 v.Chr.)" },
    henotheism: { name: "Henotheïsme en monolatrie", blurb: "Een kantelpunt: vele goden worden erkend, maar één wordt boven allen verheven — of verdient als enige verering. Achnatons korte zonnerevolutie en het vroege Israëls toewijding aan Jahweh markeren de weg naar één God.", examples: "Achnatons Aton-cultus (~1350 v.Chr.) · het vroege Israëlitische jahwisme", when: "Late bronstijd / vroege ijzertijd (~1400–600 v.Chr.)" },
    judaism: { name: "Jodendom", blurb: "Één God, schepper van alles — voor het eerst blijvend aangehangen door de Judeeërs in het ijzertijd-Israël en de Babylonische ballingschap. De wortel waaruit de andere abrahamitische geloven zouden groeien.", examples: "Israël en Juda · de Babylonische ballingschap (~6e eeuw v.Chr.) · de Joodse diaspora", when: "Vanaf de ijzertijd (~600 v.Chr.)" },
    christianity: { name: "Christendom", blurb: "Geboren in het Romeinse Judea, droeg het christendom het idee van één God door het Rijk en, door overtuiging, verovering en kolonie, naar Europa, de Amerika's en Afrika: het meest verbreide geloof op aarde.", examples: "Romeinse Rijk (~1e eeuw n.Chr.) · middeleeuws Europa · de Amerika's en Afrika (vanaf de 16e eeuw)", when: "Vanaf de 1e eeuw n.Chr." },
    islam: { name: "Islam", blurb: "Ontstaan in het 7e-eeuwse Arabië, verspreidde de islam zich met buitengewone snelheid — westwaarts tot het Iberisch Schiereiland, zuidwaarts over de Sahara en de Swahilikust, en oostwaarts tot de Indus en verder.", examples: "Arabië (~7e eeuw n.Chr.) · de kalifaten · de Sahel, de Swahilikust en Zuid-Azië", when: "Vanaf de 7e eeuw n.Chr." },
  },
  chapters: [
    { t: "Een Afrikaanse dageraad", b: "Zo'n 300.000 jaar geleden verschijnt, in de savannen en aan de kusten van Afrika, een nieuw soort mens: Homo sapiens. Lichter gebouwd en rusteloos van geest, verspreidt hij zich over het continent lang voordat hij het verlaat." },
    { t: "Een verkend continent", b: "Meer dan honderd millennia lang doorkruisen moderne mensen Afrika, verfijnen werktuigen, pigmenten en sieraden, en misschien de eerste overtuigingen dat de wereld leeft van geest." },
    { t: "Uit Afrika", b: "Zo'n 70.000 jaar geleden steekt een kleine bevolking de monding van de Rode Zee over naar Arabië. Elke niet-Afrikaan die vandaag leeft, stamt grotendeels af van deze verspreiding: een tocht die elk bewoonbaar continent zal bereiken." },
    { t: "Een wereld van jagers", b: "Mensen overspoelen Australië, Europa en het hart van Azië. In beschilderde grotten en in trance overbruggen sjamanen de werelden; clans binden zich aan totems en aan het land." },
    { t: "Het ijs en de Nieuwe Wereld", b: "Door de laatste ijstijd dringen jagers Siberië binnen en steken de Beringia-landbrug over naar de Amerika's, in enkele duizenden jaren zuidwaarts snellend tot de punt van het continent." },
    { t: "De eerste dorpen", b: "Naarmate het ijs terugtrekt, vestigen mensen zich, verbouwen en bouwen. De doden blijven onder de levenden als geëerde voorouders; in Göbekli Tepe richten mensen monumenten op voordat ze steden bouwen." },
    { t: "Goden van de eerste steden", b: "In Mesopotamië en Egypte kronen de eerste staten zich met grote pantheons. Tempels slaan graan en kennis op; een priesterschap schrijft de wil van de goden de wereld in." },
    { t: "Een tijd van gisting", b: "Van Perzië tot de Middellandse Zee en India roeren nieuwe visioenen zich — kosmisch dualisme, burgerlijke goden, en het gewaagde idee dat één God boven alle andere zou kunnen staan, of in hun plaats." },
    { t: "Eén God, vele volkeren", b: "Gedragen door rijk, handel en overtuiging verspreidt het abrahamitische monotheïsme zich over de continenten. De nakomelingen van één Afrikaanse bevolking vullen nu de aarde — en dragen de hele lange erfenis van geloof met zich mee." },
  ],
  about: {
    open: "Over", close: "Sluiten",
    title: "Over deze atlas",
    intro: "De Menselijke Reis volgt onze soort door 300.000 jaar — uit Afrika naar elk bewoonbaar continent — en traceert, naast die grote migratie, de ontvouwing van het menselijke geloof, van het eerste besef van geesten tot de wereldreligies.",
    s: [
      { h: "Wat je ziet", b: "Eén enkele globe draagt alle lagen tegelijk. Gloeiend land is bewoond land, getint met de kleur van het geloof dat daar leeft. Gestreepte cyaan lijnen zijn migratieroutes; heldere stippen markeren bereikte bewoning. Gekleurde stromen tonen geloof dat zich van plaats tot plaats verspreidt, en de roze pieken zijn de bevolking — laag in de diepe prehistorie, torenhoog in het tijdperk van de steden. Witte kappen zijn het poolijs, dat zwelt en terugtrekt met de ijstijden." },
      { h: "Hoe te navigeren", b: "Druk op Afspelen (of de spatiebalk) om het verhaal in beweging te zetten; camera, bijschriften en tijdlijn bewegen samen. Gebruik de ← en → toetsen om beeld voor beeld te stappen (of Shift + ← en → voor snellere sprongen), of sleep de tijdlijn om vrij te reizen. Sleep de globe om hem te draaien en scroll om te zoomen. Klik op een geloof in het paneel Vormen van geloof om erover te lezen en de blik te centreren; met de panelen Kaartlagen en Globetype kun je elk element tonen, verbergen en herstijlen." },
      { h: "Als lesmiddel", b: "Pauzeer op elk moment om het te bespreken. Volg hoe de omgeving migratie vormt, en hoe bewoning, landbouw, steden en geloof samen opkomen. Schakel lagen om één enkele draad te isoleren — alleen migratie, of alleen religie — en wissel de bevolkingsgrafiek tussen lineair en logaritmisch om te tonen hoe recent onze aantallen explodeerden. De bijschriften lezen als een verteld script voor een les." },
      { h: "Waarom we het maakten", b: "Niet om te betogen, maar om te verwonderen. Deze atlas is gebouwd om iedereen de lange, onwaarschijnlijke boog van de menselijke oorsprong te laten overzien — één rusteloos Afrikaans begin dat, over tienduizend generaties, de hele aarde kwam te vullen en erover te staan verwonderen." },
    ],
    learnMore: {
      h: "Meer informatie",
      b: "Deze atlas is een synthese, geen bron. Om dieper in de migratie, de genetica en de geschiedenis van geloof te duiken, zijn dit goede startpunten:",
      links: [
        { label: "Smithsonian — What Does It Mean to Be Human?", url: "https://humanorigins.si.edu/", note: "menselijke evolutie en oorsprong" },
        { label: "Bradshaw Foundation — The Journey of Mankind", url: "https://www.bradshawfoundation.com/journey/", note: "genetische kaart van de migratie" },
        { label: "Our World in Data — Population Growth", url: "https://ourworldindata.org/population-growth", note: "de lange demografische curve" },
        { label: "Britannica — The Study of Religion", url: "https://www.britannica.com/topic/study-of-religion", note: "de geschiedenis van geloof" },
        { label: "Y. N. Harari — Sapiens", url: "https://www.ynharari.com/book/sapiens-2/", note: "een kleine geschiedenis van de mensheid" },
      ],
    },
  },
};
